language: minimal

script:
  - docker build -t makepkg .
  - git clone https://aur.archlinux.org/kodi-devel.git kodi
  - mkdir cache
  - docker run -v cache:/home/builder/.ccache -v kodi:/home/builder/pkg makepkg bash -c 'cd ~/pkg && makepkg -Acs'

