language: minimal

script:
  - docker build -t makepkg .
  - git clone https://aur.archlinux.org/kodi-devel.git kodi
  - mkdir -p cache
  - docker run -v "$(pwd)"/cache:/home/builder/.ccache -v "$(pwd)"/kodi:/home/builder/pkg -it makepkg bash -c 'cd ~/pkg && makepkg -Acs --noconfirm'

cache:
  directories:
    - cache

