# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    - name: git Actions
      uses: srt32/git-actions@v0.0.3
      args: git clone https://aur.archlinux.org/kodi-devel.git
    - name: Arch Linux PKGBUILD builder action
      uses: 2m/arch-pkgbuild-builder@v1.9
      with:
        pkgname: kodi-devel-rebuilt
